### ISSUE TITLE
BOM for 2.0

### ISSUE THREAD

**Issue by bigmt** [revarbat/snappy-reprap#13]
I am currently printing all of the parts for Snappy 2.0.  I believe the BOM page is missing the bridge segment.  It is in the STL repository, so no issues finding it, but I believe the reference from the BOM is missing.  Great work on the design, I'm having a great time printing everything.  I'm using PETG and am a little concerned with the static friction on the rail segments being a bit high, but will report back if I have any issues.

**Comment by revarbat** [comment]
Whoops. Missing bridge segment added to BOM. 

You may need to experiment with lubricants for PETG. I use mineral oil for PLA and ABS. Maybe a dry Lubricant like PTFE spray on lube will work. 

I suspect the bridge segment may be a couple millimeters too long, by the way. Though I'm unclear if my issues were due to design or warped printing. I had to separate the base of one tower from the X rail by a couple mm to get the Z movement to not stall. I kinda took a break from working on v2 after MakerFaire, so I haven't gotten back to it yet.
