### ISSUE TITLE
include slop calibrator in the instructions

### ISSUE THREAD

**Issue by drunkscientist** [revarbat/snappy-reprap#28]
so after printing basically an entire x or y segment (motor+2 rails, 3 carriage pieces and bed mount parts) i opened the slop calibrator file and found that its not some new(to me) bed leveling thing but in fact for calibrating the files to the printer somehow. maybe there could be some mention of what to do with it for those who arent necessarily familiar with openscad as like, step one of the instructions?

**Comment by Erhannis** [comment]
The v3.0 BOM includes links to download the STL files, _including_ the slop calibrator.  The inclusion of download links implies "these files should work if you print them", but including the slop calibrator as a thing to print implies "you'll need to use this", which conflictingly implies you'll need to measure the slop and regenerate the other STLs rather than use the provided files.  What are we supposed to do?

**Comment by revarbat** [comment]
I added instructions for the Slop Calibrator to the BOM.
